User.create!(name: "Cesar",
            ci: 12312312,
            email: "holacomo@estas.com",
            password: 'foobar',
            password_confirmation: 'foobar')

Training.create!(hora: "7:00am",
                 cantidad: 24)
Training.create!(hora: "8:00am",
                 cantidad: 24)
Training.create!(hora: "9:00am",
                 cantidad: 24)
Training.create!(hora: "10:00am",
                 cantidad: 24)
Training.create!(hora: "11:00am",
                 cantidad: 24)
Training.create!(hora: "12:00m",
                 cantidad: 24)
Training.create!(hora: "1:00pm",
                 cantidad: 24)
Training.create!(hora: "2:00pm",
                 cantidad: 24)
Training.create!(hora: "3:00pm",
                 cantidad: 24)
Training.create!(hora: "4:00pm",
                 cantidad: 24)
Training.create!(hora: "5:00pm",
                 cantidad: 24)
Training.create!(hora: "6:00pm",
                 cantidad: 24)
Training.create!(hora: "7:00pm",
                 cantidad: 24)
Training.create!(hora: "8:00pm",
                 cantidad: 24)
